# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'feature**' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Run Tests and Linting
      run: |
        npm test
        npm run lint
